"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.label_pb2
import google.api.launch_stage_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MetricDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _MetricKind(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MetricKind.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        METRIC_KIND_UNSPECIFIED = MetricDescriptor.MetricKind.V(0)
        GAUGE = MetricDescriptor.MetricKind.V(1)
        DELTA = MetricDescriptor.MetricKind.V(2)
        CUMULATIVE = MetricDescriptor.MetricKind.V(3)
    class MetricKind(metaclass=_MetricKind):
        V = typing.NewType('V', builtins.int)
    METRIC_KIND_UNSPECIFIED = MetricDescriptor.MetricKind.V(0)
    GAUGE = MetricDescriptor.MetricKind.V(1)
    DELTA = MetricDescriptor.MetricKind.V(2)
    CUMULATIVE = MetricDescriptor.MetricKind.V(3)

    class _ValueType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ValueType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        VALUE_TYPE_UNSPECIFIED = MetricDescriptor.ValueType.V(0)
        BOOL = MetricDescriptor.ValueType.V(1)
        INT64 = MetricDescriptor.ValueType.V(2)
        DOUBLE = MetricDescriptor.ValueType.V(3)
        STRING = MetricDescriptor.ValueType.V(4)
        DISTRIBUTION = MetricDescriptor.ValueType.V(5)
        MONEY = MetricDescriptor.ValueType.V(6)
    class ValueType(metaclass=_ValueType):
        V = typing.NewType('V', builtins.int)
    VALUE_TYPE_UNSPECIFIED = MetricDescriptor.ValueType.V(0)
    BOOL = MetricDescriptor.ValueType.V(1)
    INT64 = MetricDescriptor.ValueType.V(2)
    DOUBLE = MetricDescriptor.ValueType.V(3)
    STRING = MetricDescriptor.ValueType.V(4)
    DISTRIBUTION = MetricDescriptor.ValueType.V(5)
    MONEY = MetricDescriptor.ValueType.V(6)

    class MetricDescriptorMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        LAUNCH_STAGE_FIELD_NUMBER: builtins.int
        SAMPLE_PERIOD_FIELD_NUMBER: builtins.int
        INGEST_DELAY_FIELD_NUMBER: builtins.int
        launch_stage: google.api.launch_stage_pb2.LaunchStage.V = ...

        @property
        def sample_period(self) -> google.protobuf.duration_pb2.Duration: ...

        @property
        def ingest_delay(self) -> google.protobuf.duration_pb2.Duration: ...

        def __init__(self,
            *,
            launch_stage : google.api.launch_stage_pb2.LaunchStage.V = ...,
            sample_period : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
            ingest_delay : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"ingest_delay",b"ingest_delay",u"sample_period",b"sample_period"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"ingest_delay",b"ingest_delay",u"launch_stage",b"launch_stage",u"sample_period",b"sample_period"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    METRIC_KIND_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    LAUNCH_STAGE_FIELD_NUMBER: builtins.int
    MONITORED_RESOURCE_TYPES_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    type: typing.Text = ...
    metric_kind: global___MetricDescriptor.MetricKind.V = ...
    value_type: global___MetricDescriptor.ValueType.V = ...
    unit: typing.Text = ...
    description: typing.Text = ...
    display_name: typing.Text = ...
    launch_stage: google.api.launch_stage_pb2.LaunchStage.V = ...
    monitored_resource_types: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.api.label_pb2.LabelDescriptor]: ...

    @property
    def metadata(self) -> global___MetricDescriptor.MetricDescriptorMetadata: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        type : typing.Text = ...,
        labels : typing.Optional[typing.Iterable[google.api.label_pb2.LabelDescriptor]] = ...,
        metric_kind : global___MetricDescriptor.MetricKind.V = ...,
        value_type : global___MetricDescriptor.ValueType.V = ...,
        unit : typing.Text = ...,
        description : typing.Text = ...,
        display_name : typing.Text = ...,
        metadata : typing.Optional[global___MetricDescriptor.MetricDescriptorMetadata] = ...,
        launch_stage : google.api.launch_stage_pb2.LaunchStage.V = ...,
        monitored_resource_types : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"metadata",b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"description",b"description",u"display_name",b"display_name",u"labels",b"labels",u"launch_stage",b"launch_stage",u"metadata",b"metadata",u"metric_kind",b"metric_kind",u"monitored_resource_types",b"monitored_resource_types",u"name",b"name",u"type",b"type",u"unit",b"unit",u"value_type",b"value_type"]) -> None: ...
global___MetricDescriptor = MetricDescriptor

class Metric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    type: typing.Text = ...

    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...

    def __init__(self,
        *,
        type : typing.Text = ...,
        labels : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"labels",b"labels",u"type",b"type"]) -> None: ...
global___Metric = Metric
