# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.distribution_pb2 import (
    Distribution as google___api___distribution_pb2___Distribution,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.duration_pb2 import (
    Duration as google___protobuf___duration_pb2___Duration,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

ComparisonTypeValue = typing___NewType('ComparisonTypeValue', builtin___int)
type___ComparisonTypeValue = ComparisonTypeValue
ComparisonType: _ComparisonType
class _ComparisonType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ComparisonTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    COMPARISON_UNSPECIFIED = typing___cast(ComparisonTypeValue, 0)
    COMPARISON_GT = typing___cast(ComparisonTypeValue, 1)
    COMPARISON_GE = typing___cast(ComparisonTypeValue, 2)
    COMPARISON_LT = typing___cast(ComparisonTypeValue, 3)
    COMPARISON_LE = typing___cast(ComparisonTypeValue, 4)
    COMPARISON_EQ = typing___cast(ComparisonTypeValue, 5)
    COMPARISON_NE = typing___cast(ComparisonTypeValue, 6)
COMPARISON_UNSPECIFIED = typing___cast(ComparisonTypeValue, 0)
COMPARISON_GT = typing___cast(ComparisonTypeValue, 1)
COMPARISON_GE = typing___cast(ComparisonTypeValue, 2)
COMPARISON_LT = typing___cast(ComparisonTypeValue, 3)
COMPARISON_LE = typing___cast(ComparisonTypeValue, 4)
COMPARISON_EQ = typing___cast(ComparisonTypeValue, 5)
COMPARISON_NE = typing___cast(ComparisonTypeValue, 6)
type___ComparisonType = ComparisonType

ServiceTierValue = typing___NewType('ServiceTierValue', builtin___int)
type___ServiceTierValue = ServiceTierValue
ServiceTier: _ServiceTier
class _ServiceTier(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[ServiceTierValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    SERVICE_TIER_UNSPECIFIED = typing___cast(ServiceTierValue, 0)
    SERVICE_TIER_BASIC = typing___cast(ServiceTierValue, 1)
    SERVICE_TIER_PREMIUM = typing___cast(ServiceTierValue, 2)
SERVICE_TIER_UNSPECIFIED = typing___cast(ServiceTierValue, 0)
SERVICE_TIER_BASIC = typing___cast(ServiceTierValue, 1)
SERVICE_TIER_PREMIUM = typing___cast(ServiceTierValue, 2)
type___ServiceTier = ServiceTier

class TypedValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    bool_value: builtin___bool = ...
    int64_value: builtin___int = ...
    double_value: builtin___float = ...
    string_value: typing___Text = ...

    @property
    def distribution_value(self) -> google___api___distribution_pb2___Distribution: ...

    def __init__(self,
        *,
        bool_value : typing___Optional[builtin___bool] = None,
        int64_value : typing___Optional[builtin___int] = None,
        double_value : typing___Optional[builtin___float] = None,
        string_value : typing___Optional[typing___Text] = None,
        distribution_value : typing___Optional[google___api___distribution_pb2___Distribution] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"distribution_value",b"distribution_value",u"double_value",b"double_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"distribution_value",b"distribution_value",u"double_value",b"double_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["bool_value","int64_value","double_value","string_value","distribution_value"]: ...
type___TypedValue = TypedValue

class TimeInterval(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def end_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def start_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        end_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        start_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"end_time",b"end_time",u"start_time",b"start_time"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"end_time",b"end_time",u"start_time",b"start_time"]) -> None: ...
type___TimeInterval = TimeInterval

class Aggregation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    AlignerValue = typing___NewType('AlignerValue', builtin___int)
    type___AlignerValue = AlignerValue
    Aligner: _Aligner
    class _Aligner(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Aggregation.AlignerValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        ALIGN_NONE = typing___cast(Aggregation.AlignerValue, 0)
        ALIGN_DELTA = typing___cast(Aggregation.AlignerValue, 1)
        ALIGN_RATE = typing___cast(Aggregation.AlignerValue, 2)
        ALIGN_INTERPOLATE = typing___cast(Aggregation.AlignerValue, 3)
        ALIGN_NEXT_OLDER = typing___cast(Aggregation.AlignerValue, 4)
        ALIGN_MIN = typing___cast(Aggregation.AlignerValue, 10)
        ALIGN_MAX = typing___cast(Aggregation.AlignerValue, 11)
        ALIGN_MEAN = typing___cast(Aggregation.AlignerValue, 12)
        ALIGN_COUNT = typing___cast(Aggregation.AlignerValue, 13)
        ALIGN_SUM = typing___cast(Aggregation.AlignerValue, 14)
        ALIGN_STDDEV = typing___cast(Aggregation.AlignerValue, 15)
        ALIGN_COUNT_TRUE = typing___cast(Aggregation.AlignerValue, 16)
        ALIGN_COUNT_FALSE = typing___cast(Aggregation.AlignerValue, 24)
        ALIGN_FRACTION_TRUE = typing___cast(Aggregation.AlignerValue, 17)
        ALIGN_PERCENTILE_99 = typing___cast(Aggregation.AlignerValue, 18)
        ALIGN_PERCENTILE_95 = typing___cast(Aggregation.AlignerValue, 19)
        ALIGN_PERCENTILE_50 = typing___cast(Aggregation.AlignerValue, 20)
        ALIGN_PERCENTILE_05 = typing___cast(Aggregation.AlignerValue, 21)
        ALIGN_PERCENT_CHANGE = typing___cast(Aggregation.AlignerValue, 23)
    ALIGN_NONE = typing___cast(Aggregation.AlignerValue, 0)
    ALIGN_DELTA = typing___cast(Aggregation.AlignerValue, 1)
    ALIGN_RATE = typing___cast(Aggregation.AlignerValue, 2)
    ALIGN_INTERPOLATE = typing___cast(Aggregation.AlignerValue, 3)
    ALIGN_NEXT_OLDER = typing___cast(Aggregation.AlignerValue, 4)
    ALIGN_MIN = typing___cast(Aggregation.AlignerValue, 10)
    ALIGN_MAX = typing___cast(Aggregation.AlignerValue, 11)
    ALIGN_MEAN = typing___cast(Aggregation.AlignerValue, 12)
    ALIGN_COUNT = typing___cast(Aggregation.AlignerValue, 13)
    ALIGN_SUM = typing___cast(Aggregation.AlignerValue, 14)
    ALIGN_STDDEV = typing___cast(Aggregation.AlignerValue, 15)
    ALIGN_COUNT_TRUE = typing___cast(Aggregation.AlignerValue, 16)
    ALIGN_COUNT_FALSE = typing___cast(Aggregation.AlignerValue, 24)
    ALIGN_FRACTION_TRUE = typing___cast(Aggregation.AlignerValue, 17)
    ALIGN_PERCENTILE_99 = typing___cast(Aggregation.AlignerValue, 18)
    ALIGN_PERCENTILE_95 = typing___cast(Aggregation.AlignerValue, 19)
    ALIGN_PERCENTILE_50 = typing___cast(Aggregation.AlignerValue, 20)
    ALIGN_PERCENTILE_05 = typing___cast(Aggregation.AlignerValue, 21)
    ALIGN_PERCENT_CHANGE = typing___cast(Aggregation.AlignerValue, 23)
    type___Aligner = Aligner

    ReducerValue = typing___NewType('ReducerValue', builtin___int)
    type___ReducerValue = ReducerValue
    Reducer: _Reducer
    class _Reducer(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Aggregation.ReducerValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        REDUCE_NONE = typing___cast(Aggregation.ReducerValue, 0)
        REDUCE_MEAN = typing___cast(Aggregation.ReducerValue, 1)
        REDUCE_MIN = typing___cast(Aggregation.ReducerValue, 2)
        REDUCE_MAX = typing___cast(Aggregation.ReducerValue, 3)
        REDUCE_SUM = typing___cast(Aggregation.ReducerValue, 4)
        REDUCE_STDDEV = typing___cast(Aggregation.ReducerValue, 5)
        REDUCE_COUNT = typing___cast(Aggregation.ReducerValue, 6)
        REDUCE_COUNT_TRUE = typing___cast(Aggregation.ReducerValue, 7)
        REDUCE_COUNT_FALSE = typing___cast(Aggregation.ReducerValue, 15)
        REDUCE_FRACTION_TRUE = typing___cast(Aggregation.ReducerValue, 8)
        REDUCE_PERCENTILE_99 = typing___cast(Aggregation.ReducerValue, 9)
        REDUCE_PERCENTILE_95 = typing___cast(Aggregation.ReducerValue, 10)
        REDUCE_PERCENTILE_50 = typing___cast(Aggregation.ReducerValue, 11)
        REDUCE_PERCENTILE_05 = typing___cast(Aggregation.ReducerValue, 12)
    REDUCE_NONE = typing___cast(Aggregation.ReducerValue, 0)
    REDUCE_MEAN = typing___cast(Aggregation.ReducerValue, 1)
    REDUCE_MIN = typing___cast(Aggregation.ReducerValue, 2)
    REDUCE_MAX = typing___cast(Aggregation.ReducerValue, 3)
    REDUCE_SUM = typing___cast(Aggregation.ReducerValue, 4)
    REDUCE_STDDEV = typing___cast(Aggregation.ReducerValue, 5)
    REDUCE_COUNT = typing___cast(Aggregation.ReducerValue, 6)
    REDUCE_COUNT_TRUE = typing___cast(Aggregation.ReducerValue, 7)
    REDUCE_COUNT_FALSE = typing___cast(Aggregation.ReducerValue, 15)
    REDUCE_FRACTION_TRUE = typing___cast(Aggregation.ReducerValue, 8)
    REDUCE_PERCENTILE_99 = typing___cast(Aggregation.ReducerValue, 9)
    REDUCE_PERCENTILE_95 = typing___cast(Aggregation.ReducerValue, 10)
    REDUCE_PERCENTILE_50 = typing___cast(Aggregation.ReducerValue, 11)
    REDUCE_PERCENTILE_05 = typing___cast(Aggregation.ReducerValue, 12)
    type___Reducer = Reducer

    per_series_aligner: type___Aggregation.AlignerValue = ...
    cross_series_reducer: type___Aggregation.ReducerValue = ...
    group_by_fields: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def alignment_period(self) -> google___protobuf___duration_pb2___Duration: ...

    def __init__(self,
        *,
        alignment_period : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        per_series_aligner : typing___Optional[type___Aggregation.AlignerValue] = None,
        cross_series_reducer : typing___Optional[type___Aggregation.ReducerValue] = None,
        group_by_fields : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"alignment_period",b"alignment_period"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"alignment_period",b"alignment_period",u"cross_series_reducer",b"cross_series_reducer",u"group_by_fields",b"group_by_fields",u"per_series_aligner",b"per_series_aligner"]) -> None: ...
type___Aggregation = Aggregation
