# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.label_pb2 import (
    LabelDescriptor as google___api___label_pb2___LabelDescriptor,
)

from google.api.metric_pb2 import (
    Metric as google___api___metric_pb2___Metric,
    MetricDescriptor as google___api___metric_pb2___MetricDescriptor,
)

from google.api.monitored_resource_pb2 import (
    MonitoredResource as google___api___monitored_resource_pb2___MonitoredResource,
    MonitoredResourceMetadata as google___api___monitored_resource_pb2___MonitoredResourceMetadata,
)

from google.cloud.monitoring_v3.proto.common_pb2 import (
    TimeInterval as google___monitoring___v3___common_pb2___TimeInterval,
    TypedValue as google___monitoring___v3___common_pb2___TypedValue,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Point(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def interval(self) -> google___monitoring___v3___common_pb2___TimeInterval: ...

    @property
    def value(self) -> google___monitoring___v3___common_pb2___TypedValue: ...

    def __init__(self,
        *,
        interval : typing___Optional[google___monitoring___v3___common_pb2___TimeInterval] = None,
        value : typing___Optional[google___monitoring___v3___common_pb2___TypedValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"interval",b"interval",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"interval",b"interval",u"value",b"value"]) -> None: ...
type___Point = Point

class TimeSeries(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    metric_kind: google___api___metric_pb2___MetricDescriptor.MetricKindValue = ...
    value_type: google___api___metric_pb2___MetricDescriptor.ValueTypeValue = ...

    @property
    def metric(self) -> google___api___metric_pb2___Metric: ...

    @property
    def resource(self) -> google___api___monitored_resource_pb2___MonitoredResource: ...

    @property
    def metadata(self) -> google___api___monitored_resource_pb2___MonitoredResourceMetadata: ...

    @property
    def points(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Point]: ...

    def __init__(self,
        *,
        metric : typing___Optional[google___api___metric_pb2___Metric] = None,
        resource : typing___Optional[google___api___monitored_resource_pb2___MonitoredResource] = None,
        metadata : typing___Optional[google___api___monitored_resource_pb2___MonitoredResourceMetadata] = None,
        metric_kind : typing___Optional[google___api___metric_pb2___MetricDescriptor.MetricKindValue] = None,
        value_type : typing___Optional[google___api___metric_pb2___MetricDescriptor.ValueTypeValue] = None,
        points : typing___Optional[typing___Iterable[type___Point]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata",u"metric",b"metric",u"resource",b"resource"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata",u"metric",b"metric",u"metric_kind",b"metric_kind",u"points",b"points",u"resource",b"resource",u"value_type",b"value_type"]) -> None: ...
type___TimeSeries = TimeSeries

class TimeSeriesDescriptor(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ValueDescriptor(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value_type: google___api___metric_pb2___MetricDescriptor.ValueTypeValue = ...
        metric_kind: google___api___metric_pb2___MetricDescriptor.MetricKindValue = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value_type : typing___Optional[google___api___metric_pb2___MetricDescriptor.ValueTypeValue] = None,
            metric_kind : typing___Optional[google___api___metric_pb2___MetricDescriptor.MetricKindValue] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"metric_kind",b"metric_kind",u"value_type",b"value_type"]) -> None: ...
    type___ValueDescriptor = ValueDescriptor


    @property
    def label_descriptors(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___label_pb2___LabelDescriptor]: ...

    @property
    def point_descriptors(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___TimeSeriesDescriptor.ValueDescriptor]: ...

    def __init__(self,
        *,
        label_descriptors : typing___Optional[typing___Iterable[google___api___label_pb2___LabelDescriptor]] = None,
        point_descriptors : typing___Optional[typing___Iterable[type___TimeSeriesDescriptor.ValueDescriptor]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"label_descriptors",b"label_descriptors",u"point_descriptors",b"point_descriptors"]) -> None: ...
type___TimeSeriesDescriptor = TimeSeriesDescriptor

class TimeSeriesData(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class PointData(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___monitoring___v3___common_pb2___TypedValue]: ...

        @property
        def time_interval(self) -> google___monitoring___v3___common_pb2___TimeInterval: ...

        def __init__(self,
            *,
            values : typing___Optional[typing___Iterable[google___monitoring___v3___common_pb2___TypedValue]] = None,
            time_interval : typing___Optional[google___monitoring___v3___common_pb2___TimeInterval] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"time_interval",b"time_interval"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"time_interval",b"time_interval",u"values",b"values"]) -> None: ...
    type___PointData = PointData


    @property
    def label_values(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___LabelValue]: ...

    @property
    def point_data(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___TimeSeriesData.PointData]: ...

    def __init__(self,
        *,
        label_values : typing___Optional[typing___Iterable[type___LabelValue]] = None,
        point_data : typing___Optional[typing___Iterable[type___TimeSeriesData.PointData]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"label_values",b"label_values",u"point_data",b"point_data"]) -> None: ...
type___TimeSeriesData = TimeSeriesData

class LabelValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    bool_value: builtin___bool = ...
    int64_value: builtin___int = ...
    string_value: typing___Text = ...

    def __init__(self,
        *,
        bool_value : typing___Optional[builtin___bool] = None,
        int64_value : typing___Optional[builtin___int] = None,
        string_value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["bool_value","int64_value","string_value"]: ...
type___LabelValue = LabelValue

class QueryError(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    message: typing___Text = ...

    @property
    def locator(self) -> type___TextLocator: ...

    def __init__(self,
        *,
        locator : typing___Optional[type___TextLocator] = None,
        message : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"locator",b"locator"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"locator",b"locator",u"message",b"message"]) -> None: ...
type___QueryError = QueryError

class TextLocator(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Position(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        line: builtin___int = ...
        column: builtin___int = ...

        def __init__(self,
            *,
            line : typing___Optional[builtin___int] = None,
            column : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"column",b"column",u"line",b"line"]) -> None: ...
    type___Position = Position

    source: typing___Text = ...
    nesting_reason: typing___Text = ...

    @property
    def start_position(self) -> type___TextLocator.Position: ...

    @property
    def end_position(self) -> type___TextLocator.Position: ...

    @property
    def nested_locator(self) -> type___TextLocator: ...

    def __init__(self,
        *,
        source : typing___Optional[typing___Text] = None,
        start_position : typing___Optional[type___TextLocator.Position] = None,
        end_position : typing___Optional[type___TextLocator.Position] = None,
        nested_locator : typing___Optional[type___TextLocator] = None,
        nesting_reason : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"end_position",b"end_position",u"nested_locator",b"nested_locator",u"start_position",b"start_position"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"end_position",b"end_position",u"nested_locator",b"nested_locator",u"nesting_reason",b"nesting_reason",u"source",b"source",u"start_position",b"start_position"]) -> None: ...
type___TextLocator = TextLocator
