# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.cloud.trace_v2.proto.trace_pb2 import (
    Span as google___devtools___cloudtrace___v2___trace_pb2___Span,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class BatchWriteSpansRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def spans(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___devtools___cloudtrace___v2___trace_pb2___Span]: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        spans : typing___Optional[typing___Iterable[google___devtools___cloudtrace___v2___trace_pb2___Span]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"spans",b"spans"]) -> None: ...
type___BatchWriteSpansRequest = BatchWriteSpansRequest
