# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from google.protobuf.wrappers_pb2 import (
    BoolValue as google___protobuf___wrappers_pb2___BoolValue,
    Int32Value as google___protobuf___wrappers_pb2___Int32Value,
)

from google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Span(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    SpanKindValue = typing___NewType('SpanKindValue', builtin___int)
    type___SpanKindValue = SpanKindValue
    SpanKind: _SpanKind
    class _SpanKind(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Span.SpanKindValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        SPAN_KIND_UNSPECIFIED = typing___cast(Span.SpanKindValue, 0)
        INTERNAL = typing___cast(Span.SpanKindValue, 1)
        SERVER = typing___cast(Span.SpanKindValue, 2)
        CLIENT = typing___cast(Span.SpanKindValue, 3)
        PRODUCER = typing___cast(Span.SpanKindValue, 4)
        CONSUMER = typing___cast(Span.SpanKindValue, 5)
    SPAN_KIND_UNSPECIFIED = typing___cast(Span.SpanKindValue, 0)
    INTERNAL = typing___cast(Span.SpanKindValue, 1)
    SERVER = typing___cast(Span.SpanKindValue, 2)
    CLIENT = typing___cast(Span.SpanKindValue, 3)
    PRODUCER = typing___cast(Span.SpanKindValue, 4)
    CONSUMER = typing___cast(Span.SpanKindValue, 5)
    type___SpanKind = SpanKind

    class Attributes(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class AttributeMapEntry(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            key: typing___Text = ...

            @property
            def value(self) -> type___AttributeValue: ...

            def __init__(self,
                *,
                key : typing___Optional[typing___Text] = None,
                value : typing___Optional[type___AttributeValue] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"value",b"value"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
        type___AttributeMapEntry = AttributeMapEntry

        dropped_attributes_count: builtin___int = ...

        @property
        def attribute_map(self) -> typing___MutableMapping[typing___Text, type___AttributeValue]: ...

        def __init__(self,
            *,
            attribute_map : typing___Optional[typing___Mapping[typing___Text, type___AttributeValue]] = None,
            dropped_attributes_count : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"attribute_map",b"attribute_map",u"dropped_attributes_count",b"dropped_attributes_count"]) -> None: ...
    type___Attributes = Attributes

    class TimeEvent(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class Annotation(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

            @property
            def description(self) -> type___TruncatableString: ...

            @property
            def attributes(self) -> type___Span.Attributes: ...

            def __init__(self,
                *,
                description : typing___Optional[type___TruncatableString] = None,
                attributes : typing___Optional[type___Span.Attributes] = None,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes",u"description",b"description"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes",u"description",b"description"]) -> None: ...
        type___Annotation = Annotation

        class MessageEvent(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            TypeValue = typing___NewType('TypeValue', builtin___int)
            type___TypeValue = TypeValue
            Type: _Type
            class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Span.TimeEvent.MessageEvent.TypeValue]):
                DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
                TYPE_UNSPECIFIED = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 0)
                SENT = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 1)
                RECEIVED = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 2)
            TYPE_UNSPECIFIED = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 0)
            SENT = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 1)
            RECEIVED = typing___cast(Span.TimeEvent.MessageEvent.TypeValue, 2)
            type___Type = Type

            type: type___Span.TimeEvent.MessageEvent.TypeValue = ...
            id: builtin___int = ...
            uncompressed_size_bytes: builtin___int = ...
            compressed_size_bytes: builtin___int = ...

            def __init__(self,
                *,
                type : typing___Optional[type___Span.TimeEvent.MessageEvent.TypeValue] = None,
                id : typing___Optional[builtin___int] = None,
                uncompressed_size_bytes : typing___Optional[builtin___int] = None,
                compressed_size_bytes : typing___Optional[builtin___int] = None,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"compressed_size_bytes",b"compressed_size_bytes",u"id",b"id",u"type",b"type",u"uncompressed_size_bytes",b"uncompressed_size_bytes"]) -> None: ...
        type___MessageEvent = MessageEvent


        @property
        def time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

        @property
        def annotation(self) -> type___Span.TimeEvent.Annotation: ...

        @property
        def message_event(self) -> type___Span.TimeEvent.MessageEvent: ...

        def __init__(self,
            *,
            time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
            annotation : typing___Optional[type___Span.TimeEvent.Annotation] = None,
            message_event : typing___Optional[type___Span.TimeEvent.MessageEvent] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"annotation",b"annotation",u"message_event",b"message_event",u"time",b"time",u"value",b"value"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotation",b"annotation",u"message_event",b"message_event",u"time",b"time",u"value",b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["annotation","message_event"]: ...
    type___TimeEvent = TimeEvent

    class TimeEvents(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        dropped_annotations_count: builtin___int = ...
        dropped_message_events_count: builtin___int = ...

        @property
        def time_event(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Span.TimeEvent]: ...

        def __init__(self,
            *,
            time_event : typing___Optional[typing___Iterable[type___Span.TimeEvent]] = None,
            dropped_annotations_count : typing___Optional[builtin___int] = None,
            dropped_message_events_count : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"dropped_annotations_count",b"dropped_annotations_count",u"dropped_message_events_count",b"dropped_message_events_count",u"time_event",b"time_event"]) -> None: ...
    type___TimeEvents = TimeEvents

    class Link(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        TypeValue = typing___NewType('TypeValue', builtin___int)
        type___TypeValue = TypeValue
        Type: _Type
        class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[Span.Link.TypeValue]):
            DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
            TYPE_UNSPECIFIED = typing___cast(Span.Link.TypeValue, 0)
            CHILD_LINKED_SPAN = typing___cast(Span.Link.TypeValue, 1)
            PARENT_LINKED_SPAN = typing___cast(Span.Link.TypeValue, 2)
        TYPE_UNSPECIFIED = typing___cast(Span.Link.TypeValue, 0)
        CHILD_LINKED_SPAN = typing___cast(Span.Link.TypeValue, 1)
        PARENT_LINKED_SPAN = typing___cast(Span.Link.TypeValue, 2)
        type___Type = Type

        trace_id: typing___Text = ...
        span_id: typing___Text = ...
        type: type___Span.Link.TypeValue = ...

        @property
        def attributes(self) -> type___Span.Attributes: ...

        def __init__(self,
            *,
            trace_id : typing___Optional[typing___Text] = None,
            span_id : typing___Optional[typing___Text] = None,
            type : typing___Optional[type___Span.Link.TypeValue] = None,
            attributes : typing___Optional[type___Span.Attributes] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes",u"span_id",b"span_id",u"trace_id",b"trace_id",u"type",b"type"]) -> None: ...
    type___Link = Link

    class Links(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        dropped_links_count: builtin___int = ...

        @property
        def link(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Span.Link]: ...

        def __init__(self,
            *,
            link : typing___Optional[typing___Iterable[type___Span.Link]] = None,
            dropped_links_count : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"dropped_links_count",b"dropped_links_count",u"link",b"link"]) -> None: ...
    type___Links = Links

    name: typing___Text = ...
    span_id: typing___Text = ...
    parent_span_id: typing___Text = ...
    span_kind: type___Span.SpanKindValue = ...

    @property
    def display_name(self) -> type___TruncatableString: ...

    @property
    def start_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def end_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def attributes(self) -> type___Span.Attributes: ...

    @property
    def stack_trace(self) -> type___StackTrace: ...

    @property
    def time_events(self) -> type___Span.TimeEvents: ...

    @property
    def links(self) -> type___Span.Links: ...

    @property
    def status(self) -> google___rpc___status_pb2___Status: ...

    @property
    def same_process_as_parent_span(self) -> google___protobuf___wrappers_pb2___BoolValue: ...

    @property
    def child_span_count(self) -> google___protobuf___wrappers_pb2___Int32Value: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        span_id : typing___Optional[typing___Text] = None,
        parent_span_id : typing___Optional[typing___Text] = None,
        display_name : typing___Optional[type___TruncatableString] = None,
        start_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        end_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        attributes : typing___Optional[type___Span.Attributes] = None,
        stack_trace : typing___Optional[type___StackTrace] = None,
        time_events : typing___Optional[type___Span.TimeEvents] = None,
        links : typing___Optional[type___Span.Links] = None,
        status : typing___Optional[google___rpc___status_pb2___Status] = None,
        same_process_as_parent_span : typing___Optional[google___protobuf___wrappers_pb2___BoolValue] = None,
        child_span_count : typing___Optional[google___protobuf___wrappers_pb2___Int32Value] = None,
        span_kind : typing___Optional[type___Span.SpanKindValue] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes",u"child_span_count",b"child_span_count",u"display_name",b"display_name",u"end_time",b"end_time",u"links",b"links",u"same_process_as_parent_span",b"same_process_as_parent_span",u"stack_trace",b"stack_trace",u"start_time",b"start_time",u"status",b"status",u"time_events",b"time_events"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"attributes",b"attributes",u"child_span_count",b"child_span_count",u"display_name",b"display_name",u"end_time",b"end_time",u"links",b"links",u"name",b"name",u"parent_span_id",b"parent_span_id",u"same_process_as_parent_span",b"same_process_as_parent_span",u"span_id",b"span_id",u"span_kind",b"span_kind",u"stack_trace",b"stack_trace",u"start_time",b"start_time",u"status",b"status",u"time_events",b"time_events"]) -> None: ...
type___Span = Span

class AttributeValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    int_value: builtin___int = ...
    bool_value: builtin___bool = ...

    @property
    def string_value(self) -> type___TruncatableString: ...

    def __init__(self,
        *,
        string_value : typing___Optional[type___TruncatableString] = None,
        int_value : typing___Optional[builtin___int] = None,
        bool_value : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"int_value",b"int_value",u"string_value",b"string_value",u"value",b"value"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bool_value",b"bool_value",u"int_value",b"int_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"value",b"value"]) -> typing_extensions___Literal["string_value","int_value","bool_value"]: ...
type___AttributeValue = AttributeValue

class StackTrace(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class StackFrame(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        line_number: builtin___int = ...
        column_number: builtin___int = ...

        @property
        def function_name(self) -> type___TruncatableString: ...

        @property
        def original_function_name(self) -> type___TruncatableString: ...

        @property
        def file_name(self) -> type___TruncatableString: ...

        @property
        def load_module(self) -> type___Module: ...

        @property
        def source_version(self) -> type___TruncatableString: ...

        def __init__(self,
            *,
            function_name : typing___Optional[type___TruncatableString] = None,
            original_function_name : typing___Optional[type___TruncatableString] = None,
            file_name : typing___Optional[type___TruncatableString] = None,
            line_number : typing___Optional[builtin___int] = None,
            column_number : typing___Optional[builtin___int] = None,
            load_module : typing___Optional[type___Module] = None,
            source_version : typing___Optional[type___TruncatableString] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"file_name",b"file_name",u"function_name",b"function_name",u"load_module",b"load_module",u"original_function_name",b"original_function_name",u"source_version",b"source_version"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"column_number",b"column_number",u"file_name",b"file_name",u"function_name",b"function_name",u"line_number",b"line_number",u"load_module",b"load_module",u"original_function_name",b"original_function_name",u"source_version",b"source_version"]) -> None: ...
    type___StackFrame = StackFrame

    class StackFrames(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        dropped_frames_count: builtin___int = ...

        @property
        def frame(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___StackTrace.StackFrame]: ...

        def __init__(self,
            *,
            frame : typing___Optional[typing___Iterable[type___StackTrace.StackFrame]] = None,
            dropped_frames_count : typing___Optional[builtin___int] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"dropped_frames_count",b"dropped_frames_count",u"frame",b"frame"]) -> None: ...
    type___StackFrames = StackFrames

    stack_trace_hash_id: builtin___int = ...

    @property
    def stack_frames(self) -> type___StackTrace.StackFrames: ...

    def __init__(self,
        *,
        stack_frames : typing___Optional[type___StackTrace.StackFrames] = None,
        stack_trace_hash_id : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"stack_frames",b"stack_frames"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"stack_frames",b"stack_frames",u"stack_trace_hash_id",b"stack_trace_hash_id"]) -> None: ...
type___StackTrace = StackTrace

class Module(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def module(self) -> type___TruncatableString: ...

    @property
    def build_id(self) -> type___TruncatableString: ...

    def __init__(self,
        *,
        module : typing___Optional[type___TruncatableString] = None,
        build_id : typing___Optional[type___TruncatableString] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"build_id",b"build_id",u"module",b"module"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"build_id",b"build_id",u"module",b"module"]) -> None: ...
type___Module = Module

class TruncatableString(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    value: typing___Text = ...
    truncated_byte_count: builtin___int = ...

    def __init__(self,
        *,
        value : typing___Optional[typing___Text] = None,
        truncated_byte_count : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"truncated_byte_count",b"truncated_byte_count",u"value",b"value"]) -> None: ...
type___TruncatableString = TruncatableString
