"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import google.rpc.status_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Span(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _SpanKind(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SpanKind.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        SPAN_KIND_UNSPECIFIED = Span.SpanKind.V(0)
        INTERNAL = Span.SpanKind.V(1)
        SERVER = Span.SpanKind.V(2)
        CLIENT = Span.SpanKind.V(3)
        PRODUCER = Span.SpanKind.V(4)
        CONSUMER = Span.SpanKind.V(5)
    class SpanKind(metaclass=_SpanKind):
        V = typing.NewType('V', builtins.int)
    SPAN_KIND_UNSPECIFIED = Span.SpanKind.V(0)
    INTERNAL = Span.SpanKind.V(1)
    SERVER = Span.SpanKind.V(2)
    CLIENT = Span.SpanKind.V(3)
    PRODUCER = Span.SpanKind.V(4)
    CONSUMER = Span.SpanKind.V(5)

    class Attributes(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class AttributeMapEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: typing.Text = ...

            @property
            def value(self) -> global___AttributeValue: ...

            def __init__(self,
                *,
                key : typing.Text = ...,
                value : typing.Optional[global___AttributeValue] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"value",b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

        ATTRIBUTE_MAP_FIELD_NUMBER: builtins.int
        DROPPED_ATTRIBUTES_COUNT_FIELD_NUMBER: builtins.int
        dropped_attributes_count: builtins.int = ...

        @property
        def attribute_map(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___AttributeValue]: ...

        def __init__(self,
            *,
            attribute_map : typing.Optional[typing.Mapping[typing.Text, global___AttributeValue]] = ...,
            dropped_attributes_count : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"attribute_map",b"attribute_map",u"dropped_attributes_count",b"dropped_attributes_count"]) -> None: ...

    class TimeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class Annotation(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            DESCRIPTION_FIELD_NUMBER: builtins.int
            ATTRIBUTES_FIELD_NUMBER: builtins.int

            @property
            def description(self) -> global___TruncatableString: ...

            @property
            def attributes(self) -> global___Span.Attributes: ...

            def __init__(self,
                *,
                description : typing.Optional[global___TruncatableString] = ...,
                attributes : typing.Optional[global___Span.Attributes] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"description",b"description"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"description",b"description"]) -> None: ...

        class MessageEvent(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            class _Type(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Type.V], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
                TYPE_UNSPECIFIED = Span.TimeEvent.MessageEvent.Type.V(0)
                SENT = Span.TimeEvent.MessageEvent.Type.V(1)
                RECEIVED = Span.TimeEvent.MessageEvent.Type.V(2)
            class Type(metaclass=_Type):
                V = typing.NewType('V', builtins.int)
            TYPE_UNSPECIFIED = Span.TimeEvent.MessageEvent.Type.V(0)
            SENT = Span.TimeEvent.MessageEvent.Type.V(1)
            RECEIVED = Span.TimeEvent.MessageEvent.Type.V(2)

            TYPE_FIELD_NUMBER: builtins.int
            ID_FIELD_NUMBER: builtins.int
            UNCOMPRESSED_SIZE_BYTES_FIELD_NUMBER: builtins.int
            COMPRESSED_SIZE_BYTES_FIELD_NUMBER: builtins.int
            type: global___Span.TimeEvent.MessageEvent.Type.V = ...
            id: builtins.int = ...
            uncompressed_size_bytes: builtins.int = ...
            compressed_size_bytes: builtins.int = ...

            def __init__(self,
                *,
                type : global___Span.TimeEvent.MessageEvent.Type.V = ...,
                id : builtins.int = ...,
                uncompressed_size_bytes : builtins.int = ...,
                compressed_size_bytes : builtins.int = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"compressed_size_bytes",b"compressed_size_bytes",u"id",b"id",u"type",b"type",u"uncompressed_size_bytes",b"uncompressed_size_bytes"]) -> None: ...

        TIME_FIELD_NUMBER: builtins.int
        ANNOTATION_FIELD_NUMBER: builtins.int
        MESSAGE_EVENT_FIELD_NUMBER: builtins.int

        @property
        def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

        @property
        def annotation(self) -> global___Span.TimeEvent.Annotation: ...

        @property
        def message_event(self) -> global___Span.TimeEvent.MessageEvent: ...

        def __init__(self,
            *,
            time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
            annotation : typing.Optional[global___Span.TimeEvent.Annotation] = ...,
            message_event : typing.Optional[global___Span.TimeEvent.MessageEvent] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"annotation",b"annotation",u"message_event",b"message_event",u"time",b"time",u"value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"annotation",b"annotation",u"message_event",b"message_event",u"time",b"time",u"value",b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal[u"value",b"value"]) -> typing_extensions.Literal["annotation","message_event"]: ...

    class TimeEvents(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        TIME_EVENT_FIELD_NUMBER: builtins.int
        DROPPED_ANNOTATIONS_COUNT_FIELD_NUMBER: builtins.int
        DROPPED_MESSAGE_EVENTS_COUNT_FIELD_NUMBER: builtins.int
        dropped_annotations_count: builtins.int = ...
        dropped_message_events_count: builtins.int = ...

        @property
        def time_event(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Span.TimeEvent]: ...

        def __init__(self,
            *,
            time_event : typing.Optional[typing.Iterable[global___Span.TimeEvent]] = ...,
            dropped_annotations_count : builtins.int = ...,
            dropped_message_events_count : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"dropped_annotations_count",b"dropped_annotations_count",u"dropped_message_events_count",b"dropped_message_events_count",u"time_event",b"time_event"]) -> None: ...

    class Link(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class _Type(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Type.V], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
            TYPE_UNSPECIFIED = Span.Link.Type.V(0)
            CHILD_LINKED_SPAN = Span.Link.Type.V(1)
            PARENT_LINKED_SPAN = Span.Link.Type.V(2)
        class Type(metaclass=_Type):
            V = typing.NewType('V', builtins.int)
        TYPE_UNSPECIFIED = Span.Link.Type.V(0)
        CHILD_LINKED_SPAN = Span.Link.Type.V(1)
        PARENT_LINKED_SPAN = Span.Link.Type.V(2)

        TRACE_ID_FIELD_NUMBER: builtins.int
        SPAN_ID_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        ATTRIBUTES_FIELD_NUMBER: builtins.int
        trace_id: typing.Text = ...
        span_id: typing.Text = ...
        type: global___Span.Link.Type.V = ...

        @property
        def attributes(self) -> global___Span.Attributes: ...

        def __init__(self,
            *,
            trace_id : typing.Text = ...,
            span_id : typing.Text = ...,
            type : global___Span.Link.Type.V = ...,
            attributes : typing.Optional[global___Span.Attributes] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"span_id",b"span_id",u"trace_id",b"trace_id",u"type",b"type"]) -> None: ...

    class Links(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        LINK_FIELD_NUMBER: builtins.int
        DROPPED_LINKS_COUNT_FIELD_NUMBER: builtins.int
        dropped_links_count: builtins.int = ...

        @property
        def link(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Span.Link]: ...

        def __init__(self,
            *,
            link : typing.Optional[typing.Iterable[global___Span.Link]] = ...,
            dropped_links_count : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"dropped_links_count",b"dropped_links_count",u"link",b"link"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    SPAN_ID_FIELD_NUMBER: builtins.int
    PARENT_SPAN_ID_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    STACK_TRACE_FIELD_NUMBER: builtins.int
    TIME_EVENTS_FIELD_NUMBER: builtins.int
    LINKS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    SAME_PROCESS_AS_PARENT_SPAN_FIELD_NUMBER: builtins.int
    CHILD_SPAN_COUNT_FIELD_NUMBER: builtins.int
    SPAN_KIND_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    span_id: typing.Text = ...
    parent_span_id: typing.Text = ...
    span_kind: global___Span.SpanKind.V = ...

    @property
    def display_name(self) -> global___TruncatableString: ...

    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def attributes(self) -> global___Span.Attributes: ...

    @property
    def stack_trace(self) -> global___StackTrace: ...

    @property
    def time_events(self) -> global___Span.TimeEvents: ...

    @property
    def links(self) -> global___Span.Links: ...

    @property
    def status(self) -> google.rpc.status_pb2.Status: ...

    @property
    def same_process_as_parent_span(self) -> google.protobuf.wrappers_pb2.BoolValue: ...

    @property
    def child_span_count(self) -> google.protobuf.wrappers_pb2.Int32Value: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        span_id : typing.Text = ...,
        parent_span_id : typing.Text = ...,
        display_name : typing.Optional[global___TruncatableString] = ...,
        start_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        end_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        attributes : typing.Optional[global___Span.Attributes] = ...,
        stack_trace : typing.Optional[global___StackTrace] = ...,
        time_events : typing.Optional[global___Span.TimeEvents] = ...,
        links : typing.Optional[global___Span.Links] = ...,
        status : typing.Optional[google.rpc.status_pb2.Status] = ...,
        same_process_as_parent_span : typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
        child_span_count : typing.Optional[google.protobuf.wrappers_pb2.Int32Value] = ...,
        span_kind : global___Span.SpanKind.V = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"child_span_count",b"child_span_count",u"display_name",b"display_name",u"end_time",b"end_time",u"links",b"links",u"same_process_as_parent_span",b"same_process_as_parent_span",u"stack_trace",b"stack_trace",u"start_time",b"start_time",u"status",b"status",u"time_events",b"time_events"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"child_span_count",b"child_span_count",u"display_name",b"display_name",u"end_time",b"end_time",u"links",b"links",u"name",b"name",u"parent_span_id",b"parent_span_id",u"same_process_as_parent_span",b"same_process_as_parent_span",u"span_id",b"span_id",u"span_kind",b"span_kind",u"stack_trace",b"stack_trace",u"start_time",b"start_time",u"status",b"status",u"time_events",b"time_events"]) -> None: ...
global___Span = Span

class AttributeValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STRING_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    int_value: builtins.int = ...
    bool_value: builtins.bool = ...

    @property
    def string_value(self) -> global___TruncatableString: ...

    def __init__(self,
        *,
        string_value : typing.Optional[global___TruncatableString] = ...,
        int_value : builtins.int = ...,
        bool_value : builtins.bool = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"int_value",b"int_value",u"string_value",b"string_value",u"value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"int_value",b"int_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"value",b"value"]) -> typing_extensions.Literal["string_value","int_value","bool_value"]: ...
global___AttributeValue = AttributeValue

class StackTrace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class StackFrame(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        FUNCTION_NAME_FIELD_NUMBER: builtins.int
        ORIGINAL_FUNCTION_NAME_FIELD_NUMBER: builtins.int
        FILE_NAME_FIELD_NUMBER: builtins.int
        LINE_NUMBER_FIELD_NUMBER: builtins.int
        COLUMN_NUMBER_FIELD_NUMBER: builtins.int
        LOAD_MODULE_FIELD_NUMBER: builtins.int
        SOURCE_VERSION_FIELD_NUMBER: builtins.int
        line_number: builtins.int = ...
        column_number: builtins.int = ...

        @property
        def function_name(self) -> global___TruncatableString: ...

        @property
        def original_function_name(self) -> global___TruncatableString: ...

        @property
        def file_name(self) -> global___TruncatableString: ...

        @property
        def load_module(self) -> global___Module: ...

        @property
        def source_version(self) -> global___TruncatableString: ...

        def __init__(self,
            *,
            function_name : typing.Optional[global___TruncatableString] = ...,
            original_function_name : typing.Optional[global___TruncatableString] = ...,
            file_name : typing.Optional[global___TruncatableString] = ...,
            line_number : builtins.int = ...,
            column_number : builtins.int = ...,
            load_module : typing.Optional[global___Module] = ...,
            source_version : typing.Optional[global___TruncatableString] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"file_name",b"file_name",u"function_name",b"function_name",u"load_module",b"load_module",u"original_function_name",b"original_function_name",u"source_version",b"source_version"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"column_number",b"column_number",u"file_name",b"file_name",u"function_name",b"function_name",u"line_number",b"line_number",u"load_module",b"load_module",u"original_function_name",b"original_function_name",u"source_version",b"source_version"]) -> None: ...

    class StackFrames(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        FRAME_FIELD_NUMBER: builtins.int
        DROPPED_FRAMES_COUNT_FIELD_NUMBER: builtins.int
        dropped_frames_count: builtins.int = ...

        @property
        def frame(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StackTrace.StackFrame]: ...

        def __init__(self,
            *,
            frame : typing.Optional[typing.Iterable[global___StackTrace.StackFrame]] = ...,
            dropped_frames_count : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"dropped_frames_count",b"dropped_frames_count",u"frame",b"frame"]) -> None: ...

    STACK_FRAMES_FIELD_NUMBER: builtins.int
    STACK_TRACE_HASH_ID_FIELD_NUMBER: builtins.int
    stack_trace_hash_id: builtins.int = ...

    @property
    def stack_frames(self) -> global___StackTrace.StackFrames: ...

    def __init__(self,
        *,
        stack_frames : typing.Optional[global___StackTrace.StackFrames] = ...,
        stack_trace_hash_id : builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"stack_frames",b"stack_frames"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"stack_frames",b"stack_frames",u"stack_trace_hash_id",b"stack_trace_hash_id"]) -> None: ...
global___StackTrace = StackTrace

class Module(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MODULE_FIELD_NUMBER: builtins.int
    BUILD_ID_FIELD_NUMBER: builtins.int

    @property
    def module(self) -> global___TruncatableString: ...

    @property
    def build_id(self) -> global___TruncatableString: ...

    def __init__(self,
        *,
        module : typing.Optional[global___TruncatableString] = ...,
        build_id : typing.Optional[global___TruncatableString] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"build_id",b"build_id",u"module",b"module"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"build_id",b"build_id",u"module",b"module"]) -> None: ...
global___Module = Module

class TruncatableString(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALUE_FIELD_NUMBER: builtins.int
    TRUNCATED_BYTE_COUNT_FIELD_NUMBER: builtins.int
    value: typing.Text = ...
    truncated_byte_count: builtins.int = ...

    def __init__(self,
        *,
        value : typing.Text = ...,
        truncated_byte_count : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"truncated_byte_count",b"truncated_byte_count",u"value",b"value"]) -> None: ...
global___TruncatableString = TruncatableString
