"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.cloud.trace_v2.proto.trace_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class BatchWriteSpansRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    SPANS_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def spans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.trace_v2.proto.trace_pb2.Span]: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        spans : typing.Optional[typing.Iterable[google.cloud.trace_v2.proto.trace_pb2.Span]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"spans",b"spans"]) -> None: ...
global___BatchWriteSpansRequest = BatchWriteSpansRequest
