# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.api.label_pb2 import (
    LabelDescriptor as google___api___label_pb2___LabelDescriptor,
)

from google.api.launch_stage_pb2 import (
    LaunchStageValue as google___api___launch_stage_pb2___LaunchStageValue,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.duration_pb2 import (
    Duration as google___protobuf___duration_pb2___Duration,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class MetricDescriptor(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    MetricKindValue = typing___NewType('MetricKindValue', builtin___int)
    type___MetricKindValue = MetricKindValue
    MetricKind: _MetricKind
    class _MetricKind(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[MetricDescriptor.MetricKindValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        METRIC_KIND_UNSPECIFIED = typing___cast(MetricDescriptor.MetricKindValue, 0)
        GAUGE = typing___cast(MetricDescriptor.MetricKindValue, 1)
        DELTA = typing___cast(MetricDescriptor.MetricKindValue, 2)
        CUMULATIVE = typing___cast(MetricDescriptor.MetricKindValue, 3)
    METRIC_KIND_UNSPECIFIED = typing___cast(MetricDescriptor.MetricKindValue, 0)
    GAUGE = typing___cast(MetricDescriptor.MetricKindValue, 1)
    DELTA = typing___cast(MetricDescriptor.MetricKindValue, 2)
    CUMULATIVE = typing___cast(MetricDescriptor.MetricKindValue, 3)
    type___MetricKind = MetricKind

    ValueTypeValue = typing___NewType('ValueTypeValue', builtin___int)
    type___ValueTypeValue = ValueTypeValue
    ValueType: _ValueType
    class _ValueType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[MetricDescriptor.ValueTypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        VALUE_TYPE_UNSPECIFIED = typing___cast(MetricDescriptor.ValueTypeValue, 0)
        BOOL = typing___cast(MetricDescriptor.ValueTypeValue, 1)
        INT64 = typing___cast(MetricDescriptor.ValueTypeValue, 2)
        DOUBLE = typing___cast(MetricDescriptor.ValueTypeValue, 3)
        STRING = typing___cast(MetricDescriptor.ValueTypeValue, 4)
        DISTRIBUTION = typing___cast(MetricDescriptor.ValueTypeValue, 5)
        MONEY = typing___cast(MetricDescriptor.ValueTypeValue, 6)
    VALUE_TYPE_UNSPECIFIED = typing___cast(MetricDescriptor.ValueTypeValue, 0)
    BOOL = typing___cast(MetricDescriptor.ValueTypeValue, 1)
    INT64 = typing___cast(MetricDescriptor.ValueTypeValue, 2)
    DOUBLE = typing___cast(MetricDescriptor.ValueTypeValue, 3)
    STRING = typing___cast(MetricDescriptor.ValueTypeValue, 4)
    DISTRIBUTION = typing___cast(MetricDescriptor.ValueTypeValue, 5)
    MONEY = typing___cast(MetricDescriptor.ValueTypeValue, 6)
    type___ValueType = ValueType

    class MetricDescriptorMetadata(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        launch_stage: google___api___launch_stage_pb2___LaunchStageValue = ...

        @property
        def sample_period(self) -> google___protobuf___duration_pb2___Duration: ...

        @property
        def ingest_delay(self) -> google___protobuf___duration_pb2___Duration: ...

        def __init__(self,
            *,
            launch_stage : typing___Optional[google___api___launch_stage_pb2___LaunchStageValue] = None,
            sample_period : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
            ingest_delay : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"ingest_delay",b"ingest_delay",u"sample_period",b"sample_period"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"ingest_delay",b"ingest_delay",u"launch_stage",b"launch_stage",u"sample_period",b"sample_period"]) -> None: ...
    type___MetricDescriptorMetadata = MetricDescriptorMetadata

    name: typing___Text = ...
    type: typing___Text = ...
    metric_kind: type___MetricDescriptor.MetricKindValue = ...
    value_type: type___MetricDescriptor.ValueTypeValue = ...
    unit: typing___Text = ...
    description: typing___Text = ...
    display_name: typing___Text = ...
    launch_stage: google___api___launch_stage_pb2___LaunchStageValue = ...
    monitored_resource_types: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def labels(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___api___label_pb2___LabelDescriptor]: ...

    @property
    def metadata(self) -> type___MetricDescriptor.MetricDescriptorMetadata: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[typing___Text] = None,
        labels : typing___Optional[typing___Iterable[google___api___label_pb2___LabelDescriptor]] = None,
        metric_kind : typing___Optional[type___MetricDescriptor.MetricKindValue] = None,
        value_type : typing___Optional[type___MetricDescriptor.ValueTypeValue] = None,
        unit : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        display_name : typing___Optional[typing___Text] = None,
        metadata : typing___Optional[type___MetricDescriptor.MetricDescriptorMetadata] = None,
        launch_stage : typing___Optional[google___api___launch_stage_pb2___LaunchStageValue] = None,
        monitored_resource_types : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"metadata",b"metadata"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"description",b"description",u"display_name",b"display_name",u"labels",b"labels",u"launch_stage",b"launch_stage",u"metadata",b"metadata",u"metric_kind",b"metric_kind",u"monitored_resource_types",b"monitored_resource_types",u"name",b"name",u"type",b"type",u"unit",b"unit",u"value_type",b"value_type"]) -> None: ...
type___MetricDescriptor = MetricDescriptor

class Metric(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class LabelsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        value: typing___Text = ...

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...
    type___LabelsEntry = LabelsEntry

    type: typing___Text = ...

    @property
    def labels(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        type : typing___Optional[typing___Text] = None,
        labels : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"labels",b"labels",u"type",b"type"]) -> None: ...
type___Metric = Metric
