"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.cloud.monitoring_v3.proto.common_pb2
import google.cloud.monitoring_v3.proto.mutation_record_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import google.rpc.status_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class AlertPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _ConditionCombinerType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ConditionCombinerType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        COMBINE_UNSPECIFIED = AlertPolicy.ConditionCombinerType.V(0)
        AND = AlertPolicy.ConditionCombinerType.V(1)
        OR = AlertPolicy.ConditionCombinerType.V(2)
        AND_WITH_MATCHING_RESOURCE = AlertPolicy.ConditionCombinerType.V(3)
    class ConditionCombinerType(metaclass=_ConditionCombinerType):
        V = typing.NewType('V', builtins.int)
    COMBINE_UNSPECIFIED = AlertPolicy.ConditionCombinerType.V(0)
    AND = AlertPolicy.ConditionCombinerType.V(1)
    OR = AlertPolicy.ConditionCombinerType.V(2)
    AND_WITH_MATCHING_RESOURCE = AlertPolicy.ConditionCombinerType.V(3)

    class Documentation(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        CONTENT_FIELD_NUMBER: builtins.int
        MIME_TYPE_FIELD_NUMBER: builtins.int
        content: typing.Text = ...
        mime_type: typing.Text = ...

        def __init__(self,
            *,
            content : typing.Text = ...,
            mime_type : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"content",b"content",u"mime_type",b"mime_type"]) -> None: ...

    class Condition(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        class Trigger(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            COUNT_FIELD_NUMBER: builtins.int
            PERCENT_FIELD_NUMBER: builtins.int
            count: builtins.int = ...
            percent: builtins.float = ...

            def __init__(self,
                *,
                count : builtins.int = ...,
                percent : builtins.float = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"count",b"count",u"percent",b"percent",u"type",b"type"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"count",b"count",u"percent",b"percent",u"type",b"type"]) -> None: ...
            def WhichOneof(self, oneof_group: typing_extensions.Literal[u"type",b"type"]) -> typing_extensions.Literal["count","percent"]: ...

        class MetricThreshold(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            FILTER_FIELD_NUMBER: builtins.int
            AGGREGATIONS_FIELD_NUMBER: builtins.int
            DENOMINATOR_FILTER_FIELD_NUMBER: builtins.int
            DENOMINATOR_AGGREGATIONS_FIELD_NUMBER: builtins.int
            COMPARISON_FIELD_NUMBER: builtins.int
            THRESHOLD_VALUE_FIELD_NUMBER: builtins.int
            DURATION_FIELD_NUMBER: builtins.int
            TRIGGER_FIELD_NUMBER: builtins.int
            filter: typing.Text = ...
            denominator_filter: typing.Text = ...
            comparison: google.cloud.monitoring_v3.proto.common_pb2.ComparisonType.V = ...
            threshold_value: builtins.float = ...

            @property
            def aggregations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]: ...

            @property
            def denominator_aggregations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]: ...

            @property
            def duration(self) -> google.protobuf.duration_pb2.Duration: ...

            @property
            def trigger(self) -> global___AlertPolicy.Condition.Trigger: ...

            def __init__(self,
                *,
                filter : typing.Text = ...,
                aggregations : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]] = ...,
                denominator_filter : typing.Text = ...,
                denominator_aggregations : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]] = ...,
                comparison : google.cloud.monitoring_v3.proto.common_pb2.ComparisonType.V = ...,
                threshold_value : builtins.float = ...,
                duration : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
                trigger : typing.Optional[global___AlertPolicy.Condition.Trigger] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"duration",b"duration",u"trigger",b"trigger"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"aggregations",b"aggregations",u"comparison",b"comparison",u"denominator_aggregations",b"denominator_aggregations",u"denominator_filter",b"denominator_filter",u"duration",b"duration",u"filter",b"filter",u"threshold_value",b"threshold_value",u"trigger",b"trigger"]) -> None: ...

        class MetricAbsence(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            FILTER_FIELD_NUMBER: builtins.int
            AGGREGATIONS_FIELD_NUMBER: builtins.int
            DURATION_FIELD_NUMBER: builtins.int
            TRIGGER_FIELD_NUMBER: builtins.int
            filter: typing.Text = ...

            @property
            def aggregations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]: ...

            @property
            def duration(self) -> google.protobuf.duration_pb2.Duration: ...

            @property
            def trigger(self) -> global___AlertPolicy.Condition.Trigger: ...

            def __init__(self,
                *,
                filter : typing.Text = ...,
                aggregations : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.common_pb2.Aggregation]] = ...,
                duration : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
                trigger : typing.Optional[global___AlertPolicy.Condition.Trigger] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"duration",b"duration",u"trigger",b"trigger"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"aggregations",b"aggregations",u"duration",b"duration",u"filter",b"filter",u"trigger",b"trigger"]) -> None: ...

        class MonitoringQueryLanguageCondition(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
            QUERY_FIELD_NUMBER: builtins.int
            DURATION_FIELD_NUMBER: builtins.int
            TRIGGER_FIELD_NUMBER: builtins.int
            query: typing.Text = ...

            @property
            def duration(self) -> google.protobuf.duration_pb2.Duration: ...

            @property
            def trigger(self) -> global___AlertPolicy.Condition.Trigger: ...

            def __init__(self,
                *,
                query : typing.Text = ...,
                duration : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
                trigger : typing.Optional[global___AlertPolicy.Condition.Trigger] = ...,
                ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal[u"duration",b"duration",u"trigger",b"trigger"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal[u"duration",b"duration",u"query",b"query",u"trigger",b"trigger"]) -> None: ...

        NAME_FIELD_NUMBER: builtins.int
        DISPLAY_NAME_FIELD_NUMBER: builtins.int
        CONDITION_THRESHOLD_FIELD_NUMBER: builtins.int
        CONDITION_ABSENT_FIELD_NUMBER: builtins.int
        CONDITION_MONITORING_QUERY_LANGUAGE_FIELD_NUMBER: builtins.int
        name: typing.Text = ...
        display_name: typing.Text = ...

        @property
        def condition_threshold(self) -> global___AlertPolicy.Condition.MetricThreshold: ...

        @property
        def condition_absent(self) -> global___AlertPolicy.Condition.MetricAbsence: ...

        @property
        def condition_monitoring_query_language(self) -> global___AlertPolicy.Condition.MonitoringQueryLanguageCondition: ...

        def __init__(self,
            *,
            name : typing.Text = ...,
            display_name : typing.Text = ...,
            condition_threshold : typing.Optional[global___AlertPolicy.Condition.MetricThreshold] = ...,
            condition_absent : typing.Optional[global___AlertPolicy.Condition.MetricAbsence] = ...,
            condition_monitoring_query_language : typing.Optional[global___AlertPolicy.Condition.MonitoringQueryLanguageCondition] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"condition",b"condition",u"condition_absent",b"condition_absent",u"condition_monitoring_query_language",b"condition_monitoring_query_language",u"condition_threshold",b"condition_threshold"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"condition",b"condition",u"condition_absent",b"condition_absent",u"condition_monitoring_query_language",b"condition_monitoring_query_language",u"condition_threshold",b"condition_threshold",u"display_name",b"display_name",u"name",b"name"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal[u"condition",b"condition"]) -> typing_extensions.Literal["condition_threshold","condition_absent","condition_monitoring_query_language"]: ...

    class UserLabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DOCUMENTATION_FIELD_NUMBER: builtins.int
    USER_LABELS_FIELD_NUMBER: builtins.int
    CONDITIONS_FIELD_NUMBER: builtins.int
    COMBINER_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    VALIDITY_FIELD_NUMBER: builtins.int
    NOTIFICATION_CHANNELS_FIELD_NUMBER: builtins.int
    CREATION_RECORD_FIELD_NUMBER: builtins.int
    MUTATION_RECORD_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    display_name: typing.Text = ...
    combiner: global___AlertPolicy.ConditionCombinerType.V = ...
    notification_channels: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    @property
    def documentation(self) -> global___AlertPolicy.Documentation: ...

    @property
    def user_labels(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...

    @property
    def conditions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AlertPolicy.Condition]: ...

    @property
    def enabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...

    @property
    def validity(self) -> google.rpc.status_pb2.Status: ...

    @property
    def creation_record(self) -> google.cloud.monitoring_v3.proto.mutation_record_pb2.MutationRecord: ...

    @property
    def mutation_record(self) -> google.cloud.monitoring_v3.proto.mutation_record_pb2.MutationRecord: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        display_name : typing.Text = ...,
        documentation : typing.Optional[global___AlertPolicy.Documentation] = ...,
        user_labels : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        conditions : typing.Optional[typing.Iterable[global___AlertPolicy.Condition]] = ...,
        combiner : global___AlertPolicy.ConditionCombinerType.V = ...,
        enabled : typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
        validity : typing.Optional[google.rpc.status_pb2.Status] = ...,
        notification_channels : typing.Optional[typing.Iterable[typing.Text]] = ...,
        creation_record : typing.Optional[google.cloud.monitoring_v3.proto.mutation_record_pb2.MutationRecord] = ...,
        mutation_record : typing.Optional[google.cloud.monitoring_v3.proto.mutation_record_pb2.MutationRecord] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"creation_record",b"creation_record",u"documentation",b"documentation",u"enabled",b"enabled",u"mutation_record",b"mutation_record",u"validity",b"validity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"combiner",b"combiner",u"conditions",b"conditions",u"creation_record",b"creation_record",u"display_name",b"display_name",u"documentation",b"documentation",u"enabled",b"enabled",u"mutation_record",b"mutation_record",u"name",b"name",u"notification_channels",b"notification_channels",u"user_labels",b"user_labels",u"validity",b"validity"]) -> None: ...
global___AlertPolicy = AlertPolicy
