"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.distribution_pb2
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___ComparisonType = ComparisonType
class _ComparisonType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ComparisonType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    COMPARISON_UNSPECIFIED = ComparisonType.V(0)
    COMPARISON_GT = ComparisonType.V(1)
    COMPARISON_GE = ComparisonType.V(2)
    COMPARISON_LT = ComparisonType.V(3)
    COMPARISON_LE = ComparisonType.V(4)
    COMPARISON_EQ = ComparisonType.V(5)
    COMPARISON_NE = ComparisonType.V(6)
class ComparisonType(metaclass=_ComparisonType):
    V = typing.NewType('V', builtins.int)
COMPARISON_UNSPECIFIED = ComparisonType.V(0)
COMPARISON_GT = ComparisonType.V(1)
COMPARISON_GE = ComparisonType.V(2)
COMPARISON_LT = ComparisonType.V(3)
COMPARISON_LE = ComparisonType.V(4)
COMPARISON_EQ = ComparisonType.V(5)
COMPARISON_NE = ComparisonType.V(6)

global___ServiceTier = ServiceTier
class _ServiceTier(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ServiceTier.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    SERVICE_TIER_UNSPECIFIED = ServiceTier.V(0)
    SERVICE_TIER_BASIC = ServiceTier.V(1)
    SERVICE_TIER_PREMIUM = ServiceTier.V(2)
class ServiceTier(metaclass=_ServiceTier):
    V = typing.NewType('V', builtins.int)
SERVICE_TIER_UNSPECIFIED = ServiceTier.V(0)
SERVICE_TIER_BASIC = ServiceTier.V(1)
SERVICE_TIER_PREMIUM = ServiceTier.V(2)

class TypedValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    DISTRIBUTION_VALUE_FIELD_NUMBER: builtins.int
    bool_value: builtins.bool = ...
    int64_value: builtins.int = ...
    double_value: builtins.float = ...
    string_value: typing.Text = ...

    @property
    def distribution_value(self) -> google.api.distribution_pb2.Distribution: ...

    def __init__(self,
        *,
        bool_value : builtins.bool = ...,
        int64_value : builtins.int = ...,
        double_value : builtins.float = ...,
        string_value : typing.Text = ...,
        distribution_value : typing.Optional[google.api.distribution_pb2.Distribution] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"distribution_value",b"distribution_value",u"double_value",b"double_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"distribution_value",b"distribution_value",u"double_value",b"double_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"value",b"value"]) -> typing_extensions.Literal["bool_value","int64_value","double_value","string_value","distribution_value"]: ...
global___TypedValue = TypedValue

class TimeInterval(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    END_TIME_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        end_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        start_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"end_time",b"end_time",u"start_time",b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"end_time",b"end_time",u"start_time",b"start_time"]) -> None: ...
global___TimeInterval = TimeInterval

class Aggregation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Aligner(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Aligner.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        ALIGN_NONE = Aggregation.Aligner.V(0)
        ALIGN_DELTA = Aggregation.Aligner.V(1)
        ALIGN_RATE = Aggregation.Aligner.V(2)
        ALIGN_INTERPOLATE = Aggregation.Aligner.V(3)
        ALIGN_NEXT_OLDER = Aggregation.Aligner.V(4)
        ALIGN_MIN = Aggregation.Aligner.V(10)
        ALIGN_MAX = Aggregation.Aligner.V(11)
        ALIGN_MEAN = Aggregation.Aligner.V(12)
        ALIGN_COUNT = Aggregation.Aligner.V(13)
        ALIGN_SUM = Aggregation.Aligner.V(14)
        ALIGN_STDDEV = Aggregation.Aligner.V(15)
        ALIGN_COUNT_TRUE = Aggregation.Aligner.V(16)
        ALIGN_COUNT_FALSE = Aggregation.Aligner.V(24)
        ALIGN_FRACTION_TRUE = Aggregation.Aligner.V(17)
        ALIGN_PERCENTILE_99 = Aggregation.Aligner.V(18)
        ALIGN_PERCENTILE_95 = Aggregation.Aligner.V(19)
        ALIGN_PERCENTILE_50 = Aggregation.Aligner.V(20)
        ALIGN_PERCENTILE_05 = Aggregation.Aligner.V(21)
        ALIGN_PERCENT_CHANGE = Aggregation.Aligner.V(23)
    class Aligner(metaclass=_Aligner):
        V = typing.NewType('V', builtins.int)
    ALIGN_NONE = Aggregation.Aligner.V(0)
    ALIGN_DELTA = Aggregation.Aligner.V(1)
    ALIGN_RATE = Aggregation.Aligner.V(2)
    ALIGN_INTERPOLATE = Aggregation.Aligner.V(3)
    ALIGN_NEXT_OLDER = Aggregation.Aligner.V(4)
    ALIGN_MIN = Aggregation.Aligner.V(10)
    ALIGN_MAX = Aggregation.Aligner.V(11)
    ALIGN_MEAN = Aggregation.Aligner.V(12)
    ALIGN_COUNT = Aggregation.Aligner.V(13)
    ALIGN_SUM = Aggregation.Aligner.V(14)
    ALIGN_STDDEV = Aggregation.Aligner.V(15)
    ALIGN_COUNT_TRUE = Aggregation.Aligner.V(16)
    ALIGN_COUNT_FALSE = Aggregation.Aligner.V(24)
    ALIGN_FRACTION_TRUE = Aggregation.Aligner.V(17)
    ALIGN_PERCENTILE_99 = Aggregation.Aligner.V(18)
    ALIGN_PERCENTILE_95 = Aggregation.Aligner.V(19)
    ALIGN_PERCENTILE_50 = Aggregation.Aligner.V(20)
    ALIGN_PERCENTILE_05 = Aggregation.Aligner.V(21)
    ALIGN_PERCENT_CHANGE = Aggregation.Aligner.V(23)

    class _Reducer(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Reducer.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        REDUCE_NONE = Aggregation.Reducer.V(0)
        REDUCE_MEAN = Aggregation.Reducer.V(1)
        REDUCE_MIN = Aggregation.Reducer.V(2)
        REDUCE_MAX = Aggregation.Reducer.V(3)
        REDUCE_SUM = Aggregation.Reducer.V(4)
        REDUCE_STDDEV = Aggregation.Reducer.V(5)
        REDUCE_COUNT = Aggregation.Reducer.V(6)
        REDUCE_COUNT_TRUE = Aggregation.Reducer.V(7)
        REDUCE_COUNT_FALSE = Aggregation.Reducer.V(15)
        REDUCE_FRACTION_TRUE = Aggregation.Reducer.V(8)
        REDUCE_PERCENTILE_99 = Aggregation.Reducer.V(9)
        REDUCE_PERCENTILE_95 = Aggregation.Reducer.V(10)
        REDUCE_PERCENTILE_50 = Aggregation.Reducer.V(11)
        REDUCE_PERCENTILE_05 = Aggregation.Reducer.V(12)
    class Reducer(metaclass=_Reducer):
        V = typing.NewType('V', builtins.int)
    REDUCE_NONE = Aggregation.Reducer.V(0)
    REDUCE_MEAN = Aggregation.Reducer.V(1)
    REDUCE_MIN = Aggregation.Reducer.V(2)
    REDUCE_MAX = Aggregation.Reducer.V(3)
    REDUCE_SUM = Aggregation.Reducer.V(4)
    REDUCE_STDDEV = Aggregation.Reducer.V(5)
    REDUCE_COUNT = Aggregation.Reducer.V(6)
    REDUCE_COUNT_TRUE = Aggregation.Reducer.V(7)
    REDUCE_COUNT_FALSE = Aggregation.Reducer.V(15)
    REDUCE_FRACTION_TRUE = Aggregation.Reducer.V(8)
    REDUCE_PERCENTILE_99 = Aggregation.Reducer.V(9)
    REDUCE_PERCENTILE_95 = Aggregation.Reducer.V(10)
    REDUCE_PERCENTILE_50 = Aggregation.Reducer.V(11)
    REDUCE_PERCENTILE_05 = Aggregation.Reducer.V(12)

    ALIGNMENT_PERIOD_FIELD_NUMBER: builtins.int
    PER_SERIES_ALIGNER_FIELD_NUMBER: builtins.int
    CROSS_SERIES_REDUCER_FIELD_NUMBER: builtins.int
    GROUP_BY_FIELDS_FIELD_NUMBER: builtins.int
    per_series_aligner: global___Aggregation.Aligner.V = ...
    cross_series_reducer: global___Aggregation.Reducer.V = ...
    group_by_fields: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    @property
    def alignment_period(self) -> google.protobuf.duration_pb2.Duration: ...

    def __init__(self,
        *,
        alignment_period : typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        per_series_aligner : global___Aggregation.Aligner.V = ...,
        cross_series_reducer : global___Aggregation.Reducer.V = ...,
        group_by_fields : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"alignment_period",b"alignment_period"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"alignment_period",b"alignment_period",u"cross_series_reducer",b"cross_series_reducer",u"group_by_fields",b"group_by_fields",u"per_series_aligner",b"per_series_aligner"]) -> None: ...
global___Aggregation = Aggregation
