"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.metric_pb2
import google.api.monitored_resource_pb2
import google.cloud.monitoring_v3.proto.common_pb2
import google.cloud.monitoring_v3.proto.metric_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.rpc.status_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ListMonitoredResourceDescriptorsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    filter: typing.Text = ...
    page_size: builtins.int = ...
    page_token: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        filter : typing.Text = ...,
        page_size : builtins.int = ...,
        page_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"filter",b"filter",u"name",b"name",u"page_size",b"page_size",u"page_token",b"page_token"]) -> None: ...
global___ListMonitoredResourceDescriptorsRequest = ListMonitoredResourceDescriptorsRequest

class ListMonitoredResourceDescriptorsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RESOURCE_DESCRIPTORS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: typing.Text = ...

    @property
    def resource_descriptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.api.monitored_resource_pb2.MonitoredResourceDescriptor]: ...

    def __init__(self,
        *,
        resource_descriptors : typing.Optional[typing.Iterable[google.api.monitored_resource_pb2.MonitoredResourceDescriptor]] = ...,
        next_page_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"next_page_token",b"next_page_token",u"resource_descriptors",b"resource_descriptors"]) -> None: ...
global___ListMonitoredResourceDescriptorsResponse = ListMonitoredResourceDescriptorsResponse

class GetMonitoredResourceDescriptorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name"]) -> None: ...
global___GetMonitoredResourceDescriptorRequest = GetMonitoredResourceDescriptorRequest

class ListMetricDescriptorsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    filter: typing.Text = ...
    page_size: builtins.int = ...
    page_token: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        filter : typing.Text = ...,
        page_size : builtins.int = ...,
        page_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"filter",b"filter",u"name",b"name",u"page_size",b"page_size",u"page_token",b"page_token"]) -> None: ...
global___ListMetricDescriptorsRequest = ListMetricDescriptorsRequest

class ListMetricDescriptorsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    METRIC_DESCRIPTORS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: typing.Text = ...

    @property
    def metric_descriptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.api.metric_pb2.MetricDescriptor]: ...

    def __init__(self,
        *,
        metric_descriptors : typing.Optional[typing.Iterable[google.api.metric_pb2.MetricDescriptor]] = ...,
        next_page_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"metric_descriptors",b"metric_descriptors",u"next_page_token",b"next_page_token"]) -> None: ...
global___ListMetricDescriptorsResponse = ListMetricDescriptorsResponse

class GetMetricDescriptorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name"]) -> None: ...
global___GetMetricDescriptorRequest = GetMetricDescriptorRequest

class CreateMetricDescriptorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    METRIC_DESCRIPTOR_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def metric_descriptor(self) -> google.api.metric_pb2.MetricDescriptor: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        metric_descriptor : typing.Optional[google.api.metric_pb2.MetricDescriptor] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"metric_descriptor",b"metric_descriptor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"metric_descriptor",b"metric_descriptor",u"name",b"name"]) -> None: ...
global___CreateMetricDescriptorRequest = CreateMetricDescriptorRequest

class DeleteMetricDescriptorRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name"]) -> None: ...
global___DeleteMetricDescriptorRequest = DeleteMetricDescriptorRequest

class ListTimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _TimeSeriesView(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TimeSeriesView.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        FULL = ListTimeSeriesRequest.TimeSeriesView.V(0)
        HEADERS = ListTimeSeriesRequest.TimeSeriesView.V(1)
    class TimeSeriesView(metaclass=_TimeSeriesView):
        V = typing.NewType('V', builtins.int)
    FULL = ListTimeSeriesRequest.TimeSeriesView.V(0)
    HEADERS = ListTimeSeriesRequest.TimeSeriesView.V(1)

    NAME_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    INTERVAL_FIELD_NUMBER: builtins.int
    AGGREGATION_FIELD_NUMBER: builtins.int
    SECONDARY_AGGREGATION_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    VIEW_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    filter: typing.Text = ...
    order_by: typing.Text = ...
    view: global___ListTimeSeriesRequest.TimeSeriesView.V = ...
    page_size: builtins.int = ...
    page_token: typing.Text = ...

    @property
    def interval(self) -> google.cloud.monitoring_v3.proto.common_pb2.TimeInterval: ...

    @property
    def aggregation(self) -> google.cloud.monitoring_v3.proto.common_pb2.Aggregation: ...

    @property
    def secondary_aggregation(self) -> google.cloud.monitoring_v3.proto.common_pb2.Aggregation: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        filter : typing.Text = ...,
        interval : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.TimeInterval] = ...,
        aggregation : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.Aggregation] = ...,
        secondary_aggregation : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.Aggregation] = ...,
        order_by : typing.Text = ...,
        view : global___ListTimeSeriesRequest.TimeSeriesView.V = ...,
        page_size : builtins.int = ...,
        page_token : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"aggregation",b"aggregation",u"interval",b"interval",u"secondary_aggregation",b"secondary_aggregation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"aggregation",b"aggregation",u"filter",b"filter",u"interval",b"interval",u"name",b"name",u"order_by",b"order_by",u"page_size",b"page_size",u"page_token",b"page_token",u"secondary_aggregation",b"secondary_aggregation",u"view",b"view"]) -> None: ...
global___ListTimeSeriesRequest = ListTimeSeriesRequest

class ListTimeSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIME_SERIES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    EXECUTION_ERRORS_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    next_page_token: typing.Text = ...
    unit: typing.Text = ...

    @property
    def time_series(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries]: ...

    @property
    def execution_errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.rpc.status_pb2.Status]: ...

    def __init__(self,
        *,
        time_series : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries]] = ...,
        next_page_token : typing.Text = ...,
        execution_errors : typing.Optional[typing.Iterable[google.rpc.status_pb2.Status]] = ...,
        unit : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"execution_errors",b"execution_errors",u"next_page_token",b"next_page_token",u"time_series",b"time_series",u"unit",b"unit"]) -> None: ...
global___ListTimeSeriesResponse = ListTimeSeriesResponse

class CreateTimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    TIME_SERIES_FIELD_NUMBER: builtins.int
    name: typing.Text = ...

    @property
    def time_series(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries]: ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        time_series : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"time_series",b"time_series"]) -> None: ...
global___CreateTimeSeriesRequest = CreateTimeSeriesRequest

class CreateTimeSeriesError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIME_SERIES_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int

    @property
    def time_series(self) -> google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries: ...

    @property
    def status(self) -> google.rpc.status_pb2.Status: ...

    def __init__(self,
        *,
        time_series : typing.Optional[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeries] = ...,
        status : typing.Optional[google.rpc.status_pb2.Status] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"status",b"status",u"time_series",b"time_series"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"status",b"status",u"time_series",b"time_series"]) -> None: ...
global___CreateTimeSeriesError = CreateTimeSeriesError

class CreateTimeSeriesSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Error(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        STATUS_FIELD_NUMBER: builtins.int
        POINT_COUNT_FIELD_NUMBER: builtins.int
        point_count: builtins.int = ...

        @property
        def status(self) -> google.rpc.status_pb2.Status: ...

        def __init__(self,
            *,
            status : typing.Optional[google.rpc.status_pb2.Status] = ...,
            point_count : builtins.int = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"point_count",b"point_count",u"status",b"status"]) -> None: ...

    TOTAL_POINT_COUNT_FIELD_NUMBER: builtins.int
    SUCCESS_POINT_COUNT_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    total_point_count: builtins.int = ...
    success_point_count: builtins.int = ...

    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CreateTimeSeriesSummary.Error]: ...

    def __init__(self,
        *,
        total_point_count : builtins.int = ...,
        success_point_count : builtins.int = ...,
        errors : typing.Optional[typing.Iterable[global___CreateTimeSeriesSummary.Error]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"errors",b"errors",u"success_point_count",b"success_point_count",u"total_point_count",b"total_point_count"]) -> None: ...
global___CreateTimeSeriesSummary = CreateTimeSeriesSummary

class QueryTimeSeriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    query: typing.Text = ...
    page_size: builtins.int = ...
    page_token: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        query : typing.Text = ...,
        page_size : builtins.int = ...,
        page_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"page_size",b"page_size",u"page_token",b"page_token",u"query",b"query"]) -> None: ...
global___QueryTimeSeriesRequest = QueryTimeSeriesRequest

class QueryTimeSeriesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TIME_SERIES_DESCRIPTOR_FIELD_NUMBER: builtins.int
    TIME_SERIES_DATA_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    PARTIAL_ERRORS_FIELD_NUMBER: builtins.int
    next_page_token: typing.Text = ...

    @property
    def time_series_descriptor(self) -> google.cloud.monitoring_v3.proto.metric_pb2.TimeSeriesDescriptor: ...

    @property
    def time_series_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeriesData]: ...

    @property
    def partial_errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.rpc.status_pb2.Status]: ...

    def __init__(self,
        *,
        time_series_descriptor : typing.Optional[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeriesDescriptor] = ...,
        time_series_data : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.metric_pb2.TimeSeriesData]] = ...,
        next_page_token : typing.Text = ...,
        partial_errors : typing.Optional[typing.Iterable[google.rpc.status_pb2.Status]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"time_series_descriptor",b"time_series_descriptor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"next_page_token",b"next_page_token",u"partial_errors",b"partial_errors",u"time_series_data",b"time_series_data",u"time_series_descriptor",b"time_series_descriptor"]) -> None: ...
global___QueryTimeSeriesResponse = QueryTimeSeriesResponse

class QueryErrorList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRORS_FIELD_NUMBER: builtins.int
    ERROR_SUMMARY_FIELD_NUMBER: builtins.int
    error_summary: typing.Text = ...

    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.metric_pb2.QueryError]: ...

    def __init__(self,
        *,
        errors : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.metric_pb2.QueryError]] = ...,
        error_summary : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"error_summary",b"error_summary",u"errors",b"errors"]) -> None: ...
global___QueryErrorList = QueryErrorList
