"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.api.label_pb2
import google.api.metric_pb2
import google.api.monitored_resource_pb2
import google.cloud.monitoring_v3.proto.common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Point(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INTERVAL_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int

    @property
    def interval(self) -> google.cloud.monitoring_v3.proto.common_pb2.TimeInterval: ...

    @property
    def value(self) -> google.cloud.monitoring_v3.proto.common_pb2.TypedValue: ...

    def __init__(self,
        *,
        interval : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.TimeInterval] = ...,
        value : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.TypedValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"interval",b"interval",u"value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"interval",b"interval",u"value",b"value"]) -> None: ...
global___Point = Point

class TimeSeries(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    METRIC_FIELD_NUMBER: builtins.int
    RESOURCE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    METRIC_KIND_FIELD_NUMBER: builtins.int
    VALUE_TYPE_FIELD_NUMBER: builtins.int
    POINTS_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    metric_kind: google.api.metric_pb2.MetricDescriptor.MetricKind.V = ...
    value_type: google.api.metric_pb2.MetricDescriptor.ValueType.V = ...
    unit: typing.Text = ...

    @property
    def metric(self) -> google.api.metric_pb2.Metric: ...

    @property
    def resource(self) -> google.api.monitored_resource_pb2.MonitoredResource: ...

    @property
    def metadata(self) -> google.api.monitored_resource_pb2.MonitoredResourceMetadata: ...

    @property
    def points(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point]: ...

    def __init__(self,
        *,
        metric : typing.Optional[google.api.metric_pb2.Metric] = ...,
        resource : typing.Optional[google.api.monitored_resource_pb2.MonitoredResource] = ...,
        metadata : typing.Optional[google.api.monitored_resource_pb2.MonitoredResourceMetadata] = ...,
        metric_kind : google.api.metric_pb2.MetricDescriptor.MetricKind.V = ...,
        value_type : google.api.metric_pb2.MetricDescriptor.ValueType.V = ...,
        points : typing.Optional[typing.Iterable[global___Point]] = ...,
        unit : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"metadata",b"metadata",u"metric",b"metric",u"resource",b"resource"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"metadata",b"metadata",u"metric",b"metric",u"metric_kind",b"metric_kind",u"points",b"points",u"resource",b"resource",u"unit",b"unit",u"value_type",b"value_type"]) -> None: ...
global___TimeSeries = TimeSeries

class TimeSeriesDescriptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class ValueDescriptor(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_TYPE_FIELD_NUMBER: builtins.int
        METRIC_KIND_FIELD_NUMBER: builtins.int
        UNIT_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value_type: google.api.metric_pb2.MetricDescriptor.ValueType.V = ...
        metric_kind: google.api.metric_pb2.MetricDescriptor.MetricKind.V = ...
        unit: typing.Text = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value_type : google.api.metric_pb2.MetricDescriptor.ValueType.V = ...,
            metric_kind : google.api.metric_pb2.MetricDescriptor.MetricKind.V = ...,
            unit : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"metric_kind",b"metric_kind",u"unit",b"unit",u"value_type",b"value_type"]) -> None: ...

    LABEL_DESCRIPTORS_FIELD_NUMBER: builtins.int
    POINT_DESCRIPTORS_FIELD_NUMBER: builtins.int

    @property
    def label_descriptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.api.label_pb2.LabelDescriptor]: ...

    @property
    def point_descriptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TimeSeriesDescriptor.ValueDescriptor]: ...

    def __init__(self,
        *,
        label_descriptors : typing.Optional[typing.Iterable[google.api.label_pb2.LabelDescriptor]] = ...,
        point_descriptors : typing.Optional[typing.Iterable[global___TimeSeriesDescriptor.ValueDescriptor]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"label_descriptors",b"label_descriptors",u"point_descriptors",b"point_descriptors"]) -> None: ...
global___TimeSeriesDescriptor = TimeSeriesDescriptor

class TimeSeriesData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class PointData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        VALUES_FIELD_NUMBER: builtins.int
        TIME_INTERVAL_FIELD_NUMBER: builtins.int

        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.cloud.monitoring_v3.proto.common_pb2.TypedValue]: ...

        @property
        def time_interval(self) -> google.cloud.monitoring_v3.proto.common_pb2.TimeInterval: ...

        def __init__(self,
            *,
            values : typing.Optional[typing.Iterable[google.cloud.monitoring_v3.proto.common_pb2.TypedValue]] = ...,
            time_interval : typing.Optional[google.cloud.monitoring_v3.proto.common_pb2.TimeInterval] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"time_interval",b"time_interval"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"time_interval",b"time_interval",u"values",b"values"]) -> None: ...

    LABEL_VALUES_FIELD_NUMBER: builtins.int
    POINT_DATA_FIELD_NUMBER: builtins.int

    @property
    def label_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LabelValue]: ...

    @property
    def point_data(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TimeSeriesData.PointData]: ...

    def __init__(self,
        *,
        label_values : typing.Optional[typing.Iterable[global___LabelValue]] = ...,
        point_data : typing.Optional[typing.Iterable[global___TimeSeriesData.PointData]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"label_values",b"label_values",u"point_data",b"point_data"]) -> None: ...
global___TimeSeriesData = TimeSeriesData

class LabelValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    bool_value: builtins.bool = ...
    int64_value: builtins.int = ...
    string_value: typing.Text = ...

    def __init__(self,
        *,
        bool_value : builtins.bool = ...,
        int64_value : builtins.int = ...,
        string_value : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"bool_value",b"bool_value",u"int64_value",b"int64_value",u"string_value",b"string_value",u"value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"value",b"value"]) -> typing_extensions.Literal["bool_value","int64_value","string_value"]: ...
global___LabelValue = LabelValue

class QueryError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LOCATOR_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: typing.Text = ...

    @property
    def locator(self) -> global___TextLocator: ...

    def __init__(self,
        *,
        locator : typing.Optional[global___TextLocator] = ...,
        message : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"locator",b"locator"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"locator",b"locator",u"message",b"message"]) -> None: ...
global___QueryError = QueryError

class TextLocator(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Position(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        LINE_FIELD_NUMBER: builtins.int
        COLUMN_FIELD_NUMBER: builtins.int
        line: builtins.int = ...
        column: builtins.int = ...

        def __init__(self,
            *,
            line : builtins.int = ...,
            column : builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"column",b"column",u"line",b"line"]) -> None: ...

    SOURCE_FIELD_NUMBER: builtins.int
    START_POSITION_FIELD_NUMBER: builtins.int
    END_POSITION_FIELD_NUMBER: builtins.int
    NESTED_LOCATOR_FIELD_NUMBER: builtins.int
    NESTING_REASON_FIELD_NUMBER: builtins.int
    source: typing.Text = ...
    nesting_reason: typing.Text = ...

    @property
    def start_position(self) -> global___TextLocator.Position: ...

    @property
    def end_position(self) -> global___TextLocator.Position: ...

    @property
    def nested_locator(self) -> global___TextLocator: ...

    def __init__(self,
        *,
        source : typing.Text = ...,
        start_position : typing.Optional[global___TextLocator.Position] = ...,
        end_position : typing.Optional[global___TextLocator.Position] = ...,
        nested_locator : typing.Optional[global___TextLocator] = ...,
        nesting_reason : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"end_position",b"end_position",u"nested_locator",b"nested_locator",u"start_position",b"start_position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"end_position",b"end_position",u"nested_locator",b"nested_locator",u"nesting_reason",b"nesting_reason",u"source",b"source",u"start_position",b"start_position"]) -> None: ...
global___TextLocator = TextLocator
