"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class MutationRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MUTATE_TIME_FIELD_NUMBER: builtins.int
    MUTATED_BY_FIELD_NUMBER: builtins.int
    mutated_by: typing.Text = ...

    @property
    def mutate_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...

    def __init__(self,
        *,
        mutate_time : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        mutated_by : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"mutate_time",b"mutate_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"mutate_time",b"mutate_time",u"mutated_by",b"mutated_by"]) -> None: ...
global___MutationRecord = MutationRecord
